### PR TITLE
Add variable to distinguish master from node

### PR DESCRIPTION
**Pull request by zreigz**

### CODE REVIEW

**Comment by zreigz** [comment]
@cheld @batikanu @f-higashi please review

**Comment by batikanu** [comment]
LGTM

**Comment by f-higashi** [comment]
you need to pass config resource and executing scripts in kubeminion.yaml.

```
        - config: {get_resource: pre_tasks}
        - config: {get_resource: provision_node}
        - config: {get_resource: post_tasks}
```

**Comment by zreigz** [comment]
Yes I forget it. Thanks

**Comment by zreigz** [comment]
I pushed this directly to master

**Comment by f-higashi** [comment]
I checked it.  :+1:

**Pull request merged**
