### PR TITLE
Fix for reboot problem

### PR DESCRIPTION
**Pull request by zreigz**
I moved k8s services from image builder to provisioning part to make image minimal as possible.

### CODE REVIEW

**Comment by zreigz** [comment]
@batikanu @f-higashi @cheld please review

**Comment by cheld** [comment]
where do the binaries come from? They must be available on the image I assume. 

hmm... I don't like that. I rather would like to leave this PR pending.

We should try to get rid of docker-bootsrtap. There seem to be several options

CNI plugin Kubenet could be a solution (maybe not stable yet)

https://github.com/kubernetes/kubernetes/pull/18795/files

**Comment by zreigz** [comment]
It doesn't use any binaries. Services just start docker images using docker bootstrap service for it. Those images are available after provisioning. After system reboot it's required to start again etcd, flannel and kubelet with previous settings. This is how it works. 
There is no need to install any new things in image just start it again.

**Comment by cheld** [comment]
I think we can close this?

**Pull request closed without merging**
