### PR TITLE
heapster source is fixed to make it run in multinode docker provisioner

### PR DESCRIPTION
**Pull request by batikanu**
Old source fails in docker provisioner.

### CODE REVIEW

**Comment by batikanu** [comment]
cc @kenan435 @cheld @taimir

**Comment by zreigz** [comment]
I thought you will do the PR to hyperkube addons manager. As far I know heapster is missing in hypercube addons. Currently we will use addons from hypercube I don't see any reason to duplicate it anymore.

**Comment by batikanu** [comment]
Current heapster parameters are wrong. Independent from addon manager they have to be fixed. This PR includes only this change nothing about new implementation. Fixed heapster will be put in hypercube as next.

**Comment by zreigz** [comment]
OK thanks for explanation

**Comment by zreigz** [comment]
LGTM

**Comment by cheld** [comment]
Hyperkube in upstream is cross-compiled. However, Heapster is not cross-compiled currently. That's why it is not part of Hyperkube yet. So, we have two options.
1. Fork Hyperkube (somehow) and add Heapser in our own repo.
2. Change build scripts of Heapster to create cross-compiled Docker images

We can also fork for this sprint and contribute later

**Pull request merged**
