### PR TITLE
Remove hyperkube Dockerfile from the provisioner

### PR DESCRIPTION
**Pull request by taimir**
The modified hyperkube's Dockerfile is now maintained in the kubernetes
project under the Fujitsu github organization.

### CODE REVIEW

**Comment by taimir** [comment]
@batikanu can you review?

**Comment by cheld** [comment]
Is everything migrated to kubernetes branch?

**Comment by batikanu** [comment]
It is already in kubernetes/cluster/images/hyperkube. So LGTM

**Comment by cheld** [comment]
Then merge

**Pull request merged**
